# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: protofu
description: ProtoFu compiles protos for you! Transitive dependency tracking, protoc downloading, and more.
version: 1.0.0
repository: https://github.com/jtmcdole/protofu

environment:
  sdk: '>=2.17.6 <3.0.0'

executables:
  protofu:

dependencies:
  ansicolor: ^2.0.1
  archive: ^3.3.1
  args: ^2.3.1
  http: ^0.13.4
  meta: ^1.8.0
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  protobuf: ^2.1.0
  test: ^1.16.0
